import { uniqueId } from "lodash";

const Menuitems = [
  // {
  //   id: uniqueId(),
  //   title: "Medical Records",
  //   name: "Medical Records",
  //   url: "",
  //   icon: "solar:user-id-linear",
  //   column: 2,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "Medical Records",
  //       icon: "solar:user-id-linear",
  //       href: "/customer",
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "OPD Register",
  //       icon: "solar:user-id-linear",
  //       href: "/medical-records/opd-register",
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "Registration",
  //       icon: "solar:user-id-linear",
  //       href: "#",
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "Calendar",
  //   name: "Calendar",
  //   url: "",
  //   icon: "solar:calendar-line-duotone",
  //   href: "",
  //   column: 2,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "Calendar",
  //       icon: "solar:calendar-line-duotone",
  //       href: "/calendar",
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "Privilege Center",
  //   name: "Privilege Center",
  //   url: "",
  //   icon: "solar:user-id-bold",
  //   href: "",
  //   column: 2,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "Privilege Check",
  //       icon: "solar:user-id-bold",
  //       href: "/medical-records/medical-records-management",
  //     },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: "OPD Register",
  //     //   icon: "solar:user-id-bold",
  //     //   href: "/medical-records/opd-register",
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: "Registration",
  //     //   icon: "solar:user-id-bold",
  //     //   href: "/medical-records/patient-register",
  //     // },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "OPD Clinic",
  //   name: "OPD Clinic",
  //   url: "",
  //   icon: "solar:user-id-bold",
  //   href: "",
  //   column: 2,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "OPD Clinic",
  //       icon: "solar:user-id-bold",
  //       href: "#",
  //     },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: "OPD Register",
  //     //   icon: "solar:user-id-bold",
  //     //   href: "/medical-records/opd-register",
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: "Registration",
  //     //   icon: "solar:user-id-bold",
  //     //   href: "/medical-records/patient-register",
  //     // },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "Setting",
  //   name: "Setting",
  //   url: "",
  //   icon: "solar:settings-outline",
  //   href: "",
  //   column: 2,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "Role",
  //       icon: "solar:user-check-broken",
  //       href: "/user-tables/basic",
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "Role Management",
  //       icon: "carbon:subnet-acl-rules",
  //       href: "/user-tables/role-manage",
  //     },
  //     {
  //       id: uniqueId(),
  //       title: "Permissions",
  //       icon: "carbon:subnet-acl-rules",
  //       href: "/user-tables/permission-table",
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: "Queue Management",
  //   name: "Queue Management",
  //   url: "",
  //   icon: "solar:settings-outline",
  //   href: "",
  //   column: 2,
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: "Queue Management",
  //       icon: "solar:user-check-broken",
  //       href: "/queue-management",
  //     },
  //   ],
  // },
  {
    id: uniqueId(),
    title: "Dashboard",
    name: "Dashboard",
    url: "/",
    icon: "tabler:brand-speedtest",
    href: "",
    column: 2,
  },

  {
    id: uniqueId(),
    title: "Clinic",
    name: "Clinic",
    url: "",
    icon: "tabler:building-store",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Store Package",
    name: "Store Package",
    url: "",
    icon: "tabler:package",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Pay Notification",
    name: "Pay Notification",
    url: "",
    icon: "tabler:credit-card",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Language",
    name: "Language",
    url: "",
    icon: "tabler:language",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Permission",
    name: "Permission",
    url: "",
    icon: "tabler:key",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Menu Group",
    name: "Menu Group",
    url: "",
    icon: "tabler:adjustments",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Admin",
    name: "Admin",
    url: "",
    icon: "tabler:user-cog",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "User",
    name: "User",
    url: "",
    icon: "tabler:user",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Service Catagory Management",
    name: "Service Catagory Management",
    url: "",
    icon: "tabler:list-check",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Product Unit Management",
    name: "Product Unit Management",
    url: "",
    icon: "tabler:tags",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Popup Management",
    name: "Popup Management",
    url: "",
    icon: "tabler:alert-octagon",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "File Management",
    name: "File Management",
    url: "",
    icon: "tabler:cloud",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Data Transfer",
    name: "Data Transfer",
    url: "",
    icon: "tabler:database",
    href: "",
    column: 2,
  },
  {
    id: uniqueId(),
    title: "Cost",
    name: "Cost",
    url: "",
    icon: "tabler:plus-minus",
    column: 2,
    href: "",
    children: [],
  },
  {
    id: uniqueId(),
    title: "Report",
    name: "Report",
    url: "",
    icon: "tabler:report",
    column: 2,
    href: "",
    children: [],
  },
  {
    id: uniqueId(),
    title: "Save Log",
    name: "Save Log",
    url: "",
    icon: "tabler:list",
    column: 2,
    href: "",
    children: [],
  },
];
export default Menuitems;
